config/routes.rb
Cscone::Application.routes.draw do

  

  resources :insurance_transactions do
  get 'export',:on=>:collection
end

 

  namespace :admin do resources :insurance_premia end
  
    namespace :admin do resources :reports do
      get 'banking',:on=>:collection
      get 'insurance',:on=>:collection
      get 'insurance_transaction',:on=>:collection
      get 'banking_transaction',:on=>:collection
      post 'banking_report',:on=>:collection
      post 'banking_transaction_report',:on=>:collection
      post 'insurance_report',:on=>:collection
      post  'insurance_transaction_report',:on=>:collection
    end
   end
  namespace :admin do resources :premia do
 get 'export',:on=>:collection
end
 end

  resources :transactions do
     get 'export',:on=>:collection
   end

  namespace :admin do resources :account_types do
 get 'export',:on=>:collection
end
end

  

  resources :insurances do
 get 'export',:on=>:collection
end

  resources :bankings do
     get 'export',:on=>:collection
     get 'edit_profile',:on=>:collection
     get 'show_profile',:on=>:collection
   end
 

  namespace :admin do resources :vle_representatives do
      get 'export',:on=>:collection
      get 'vle_user',:on=>:collection
      get 'vle_document',:on=>:collection
      get 'vle_report',:on=>:collection
       post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          post 'load_csc_blocks',:on=>:collection
          post 'load_vle_representatives',:on=>:collection
        get 'disable_representative',:on=>:collection
        get 'update_vle_representative',:on=>:collection
        get 'vle_profile',:on=>:collection
         get 'edit_profile',:on=>:collection
        post 'csv_import' , :on=>:collection
         get 'upload', :on=>:collection 
         get 'reset_password',:on=>:collection
          get 'upload_password',:on=>:collection
          get 'report',:on=>:collection
          get 'bulk_mailing' , :on=>:collection
          

      end
  end

  namespace :admin do
       resources :vle_documents do
           get 'export',:on=>:collection
       end
        end

  namespace :admin do
      resources :csc_blocks do
          get 'export',:on=>:collection
          post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          end
      end

  namespace :admin do
  resources :districts do
            get 'vle_document',:on=>:collection
      post 'load_bidding_zones',:on => :collection
  get 'export', :on=>:collection
       end
end
  namespace :admin do
  resources :bidding_zones do
    get 'export',:on=>:collection
    end
   end

  namespace :admin do
      resources :states do
          get 'export' ,:on=>:collection
           post 'csv_import', :on=>:collection
  get 'upload', :on=>:collection 
       end

      end
  
    resources :user_sessions
    
 namespace :admin do
 resources :users do
  get 'export',:on=>:collection
    end

  end
  resource :accout,:controller=>'users'
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/bidding_zone.rb
class BiddingZone < ActiveRecord::Base
 belongs_to :state

 has_many :districts,:dependent=>:destroy
 has_many :csc_blocks,:dependent=>:destroy
  has_many :vle_representative_profiles,:dependent=>:destroy
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 100}
 validates :state_id, :presence => true
  validates :description, :length => { :maximum => 2000}
     def self.search(search)
    if search
      where(:name.matches => "%#{search}%") #from meta_where gem
    else
      scoped
    end
  end

end

app/controllers/admin/bidding_zones_controller.rb
require 'fastercsv'
class Admin::BiddingZonesController < ApplicationController
  
  helper_method :sort_column, :sort_direction
  layout 'admin'
  before_filter :require_user
  before_filter :recent_items

  def index
   @bidding_zones = BiddingZone.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bidding_zones }
    end
  end

  def show
    @bidding_zone = BiddingZone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bidding_zone }
    end
  end

  def new
    @bidding_zone = BiddingZone.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bidding_zone}
    end
  end

  def edit
    @bidding_zone= BiddingZone.find(params[:id])
  end

  def create
    @bidding_zone= BiddingZone.new(params[:bidding_zone])
     @bidding_zone.created_by = @created_by

    respond_to do |format|
      if @bidding_zone.save
        format.html { redirect_to([:admin,@bidding_zone], :notice => 'Bidding zone was successfully created.') }
        format.xml  { render :xml => @bidding_zone, :status => :created, :location => @bidding_zone}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bidding_zone.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @bidding_zone= BiddingZone.find(params[:id])
    @bidding_zone.updated_by = @updated_by
    respond_to do |format|
      if @bidding_zone.update_attributes(params[:bidding_zone])
        format.html { redirect_to([:admin,@bidding_zone], :notice => 'Bidding zone was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_bidding_zone.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @bidding_zone= BiddingZone.find(params[:id])
    @bidding_zone.destroy

    respond_to do |format|
      format.html { redirect_to(admin_bidding_zones_url) }
      format.xml  { head :ok }
    end
  end
   def export
    @bidding_zones = BiddingZone.search(params[:search]).order("name")
    outfile = "bidding_zones" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
   csv_data = FasterCSV.generate do |csv|
      csv << ["State Name"," Name","Description","Create at","Created By"]
      @bidding_zones.each do |bidding_zone|
        csv << [bidding_zone.state.name,bidding_zone.name,bidding_zone.description,bidding_zone.created_at.strftime('%d-%m-%Y %H:%M:%S'),User.find(bidding_zone.created_by).name]
      end
    end
    send_data csv_data,
    :type => 'text/csv; charset=iso-8859-1; header=present',
    :disposition => "attachment; filename=#{outfile}"

  end

 private

  def recent_items
    @recent_bidding_zones = BiddingZone.find(:all,:limit=>10,:order=>'created_at DESC')
  end

  def sort_column
    State.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/admin/bidding_zones/_bidding_zone.html.erb
<%content_tag_for(:tr,bidding_zone) do -%>
<td>
    <%=link_to(highlight(bidding_zone.name,params[:search]),admin_bidding_zone_path(bidding_zone)) %>
</td>
<td>
<%=h bidding_zone.state.name %>
</td>

<td>
    <%=h bidding_zone.description %>
</td>
<td>
    <%=h @created_name %>
</td>
<td>
    <%=h bidding_zone.created_at.strftime('%d-%m-%Y') %>
</td>
<td>
    <%= link_to 'Edit', edit_admin_bidding_zone_path(bidding_zone) %> |
    <%= link_to 'Delete', [:admin,bidding_zone], :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to 'View', [:admin,bidding_zone] %>
</td>
<% end %>


app/views/admin/bidding_zones/_form.html.erb
<div class="form-container">
    <% form_for([:admin,@bidding_zone],:html=>{:class=>'cmxform'}) do |f| %>
    <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
    <fieldset>
        <legend>
            <%= heading %>
        </legend>
        <%= f.error_messages %>

        <div>
            <label for="name">
                Name <em>*</em>
            </label>
            <%= f.text_field :name %>
        </div>
        <div>
        <label for=state_id">State Name
        </label>
        <%= collection_select(:bidding_zone,:state_id,State.order('name'),:id,:name,:prompt=>"Select a state") %>
        </div>
        <div>
            <label for="description ">
                Description <em>*</em>
            </label>
            <%= f.text_area :description ,:cols=>28,:rows=>5 %>
        </div>
        <div class="buttonrow">
            <%= f.submit button_name ,:class=>'button' %>
        </div>
    </fieldset>
    <% end %>
</div>


app/views/admin/bidding_zones/_recent_items.html.erb
<% for bidding_zones in @recent_bidding_zones %>
<li class="" id="recent_bidding_zones_<%= bidding_zones.id%>">
    <dt>
        <%=link_to truncate(bidding_zones.name,:length=>27),admin_bidding_zones_path(bidding_zones) %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>


app/views/admin/bidding_zones/_results.html.erb
<div id="state_list" class="list">
    <%if @bidding_zones.blank? %>
    <div class="empty">There are No Bidding Zones yet..!</div>
    <%else %>
    <table width="100%">
        <tr>
            <td align="left">
                <h3 align="left"><%=@table_heading ||= 'Listing Bidding Zones' %></h3>
            </td>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %> | <%= page_entries_info @bidding_zones %>
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>
                <th><%= sortable 'name' %></th>
                <th>State</th>
                <th>Description</th>
                <th><%= sortable "created_by" %></th>
		        <th><%= sortable "created_at" %></th>
                <th>Actions</th>
            </tr>
        </thead>
        <%=render :partial=>'bidding_zone',:collection=>@bidding_zones %>
    </table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= will_paginate @bidding_zones %>
    <% end %>
</div>


app/views/admin/bidding_zones/_state.html.erb
<%content_tag_for(:tr,state) do -%>
<td>
    <%=link_to(highlight(state.name,params[:search]),admin_state_path(state)) %>
</td>
<td>
    <%=h state.description %>
</td>
<td>
    <%=h @created_name %>
</td>
<td>
    <%=h state.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
</td>
<td>

    <%= link_to 'Edit', edit_admin_state_path(state) %>|

    <%= link_to 'Destroy', [:admin,state], :confirm => 'Are you sure?', :method => :delete %>|
    <%= link_to 'Show', [:admin,state] %>
</td>
<% end %>


app/views/admin/bidding_zones/edit.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Update',:heading=>'Edit BiddingZone'} %>
<div class="bottom_links">
    <a href="admin/bidding_zones" class="more">&larr; All Bidding Zones</a>
    <%= link_to [:admin,@bidding_zone],:class=>'more' do %>
    Show &uarr; <% end %>
</div>

app/views/admin/bidding_zones/index.html.erb
<div id="markets">
    <%=render :partial=>'results' %>
</div>

app/views/admin/bidding_zones/new.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Create',:heading=>'Create Bidding Zone'} %>
<div class="bottom_links">
    <a href="/admin/bidding_zones" class="more">&larr; List All Bidding Zones</a>
</div>

app/views/admin/bidding_zones/show.html.erb
<div class="form-container">
    <fieldset>
        <legend>
            <b><%= @bidding_zone.name %></b>
        </legend>
        <div>
        <hr/>
        <label>
                <b>State Name:</b>
            </label>
            <%=h @bidding_zone.state.name %>
        </div>
<hr/>
        <div>
            <label>
                <b>Description:</b>
            </label>
            <%=h @bidding_zone.description %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Created by:</b>
            </label>
            <%= User.find(@bidding_zone.created_by).name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Created At:</b>
            </label>
            <%= @bidding_zone.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
        </div>
    </fieldset>
</div>
<div class="bottom_links">
    <a href="/admin/bidding_zones" class="more">&larr; All Bidding Zones</a>
    &nbsp;&nbsp;
    <%= link_to edit_admin_bidding_zone_path(@bidding_zone),:class=>'more' do %>
    Edit &uarr;
    <% end %>
    &nbsp;&nbsp;
    <%=link_to new_admin_bidding_zone_path,:class=>'more' do %>
    Create New Bidding Zone &rarr;
    <% end %>
</div>