config/routes.rb
Cscone::Application.routes.draw do

  

  resources :insurance_transactions do
  get 'export',:on=>:collection
end

 

  namespace :admin do resources :insurance_premia end
  
    namespace :admin do resources :reports do
      get 'banking',:on=>:collection
      get 'insurance',:on=>:collection
      get 'insurance_transaction',:on=>:collection
      get 'banking_transaction',:on=>:collection
      post 'banking_report',:on=>:collection
      post 'banking_transaction_report',:on=>:collection
      post 'insurance_report',:on=>:collection
      post  'insurance_transaction_report',:on=>:collection
    end
   end
  namespace :admin do resources :premia do
 get 'export',:on=>:collection
end
 end

  resources :transactions do
     get 'export',:on=>:collection
   end

  namespace :admin do resources :account_types do
 get 'export',:on=>:collection
end
end

  

  resources :insurances do
 get 'export',:on=>:collection
end

  resources :bankings do
     get 'export',:on=>:collection
     get 'edit_profile',:on=>:collection
     get 'show_profile',:on=>:collection
   end
 

  namespace :admin do resources :vle_representatives do
      get 'export',:on=>:collection
      get 'vle_user',:on=>:collection
      get 'vle_document',:on=>:collection
      get 'vle_report',:on=>:collection
       post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          post 'load_csc_blocks',:on=>:collection
          post 'load_vle_representatives',:on=>:collection
        get 'disable_representative',:on=>:collection
        get 'update_vle_representative',:on=>:collection
        get 'vle_profile',:on=>:collection
         get 'edit_profile',:on=>:collection
        post 'csv_import' , :on=>:collection
         get 'upload', :on=>:collection 
         get 'reset_password',:on=>:collection
          get 'upload_password',:on=>:collection
          get 'report',:on=>:collection
          get 'bulk_mailing' , :on=>:collection
          

      end
  end

  namespace :admin do
       resources :vle_documents do
           get 'export',:on=>:collection
       end
        end

  namespace :admin do
      resources :csc_blocks do
          get 'export',:on=>:collection
          post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          end
      end

  namespace :admin do
  resources :districts do
            get 'vle_document',:on=>:collection
      post 'load_bidding_zones',:on => :collection
  get 'export', :on=>:collection
       end
end
  namespace :admin do
  resources :bidding_zones do
    get 'export',:on=>:collection
    end
   end

  namespace :admin do
      resources :states do
          get 'export' ,:on=>:collection
           post 'csv_import', :on=>:collection
  get 'upload', :on=>:collection 
       end

      end
  
    resources :user_sessions
    
 namespace :admin do
 resources :users do
  get 'export',:on=>:collection
    end

  end
  resource :accout,:controller=>'users'
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

   match ':controller(/:action(/:id(.:format)))'
end

app/controllers/transactions_controller.rb
require 'fastercsv'
class TransactionsController < ApplicationController
  helper_method :sort_column, :sort_direction
  # GET /transactions
  # GET /transactions.xml
 layout 'common'
  before_filter :require_user
  before_filter :recent_items
  def index
  @transactions = Transaction.where(:created_by=>current_user.id).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )
   
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.created_by = @created_by
    @transaction.user_id= @created_by
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])
    @transaction.updatesd_by = @updated_by
    @transaction.user_id = @created_by
    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
   def export
    @transactions = Transaction.search(params[:search]).order("bank_name")
    outfile = "transactions" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["Name","Account Number","Mode Of Transaction","Amount","Create at","Created By"]
      @transactions.each do |transaction|
        csv << [transaction.bank_name,transaction.account_number,transaction.mode_of_transaction,transaction.amount,transaction.created_at.strftime('%d-%m-%Y %H:%M:%S'),User.find(transaction.created_by).name]
      end
    end
    send_data csv_data,
    :type => 'text/csv; charset=iso-8859-1; header=present',
    :disposition => "attachment; filename=#{outfile}"

  end
private

  def recent_items
    @recent_transactions = Transaction.where(:created_by=>current_user.id)
  end

  def sort_column
    Transaction.column_names.include?(params[:sort]) ? params[:sort] : "bank_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="form-container">
<%= form_for(@transaction) do |form| %>
 <p class="legend"><strong>Note:</strong> Required fields are marked with an asterisk (<em>*</em>)</p>
<fieldset>
<legend><%=heading %></legend>

 <%= form.error_messages %>
<div>
    <label for="bank_name">Bank Name<em>*</em></label>
   <%= form.text_field :bank_name, :value=>'STATE BANK OF INDIA'%>
  </div>
<div>
    <label for="account_number">Account Number <em>*</em></label>
   <%= form.text_field :account_number %>
  </div>
  <div>
    <label for="mode_of_transaction">Mode Of Transaction <em>*</em></label>
   <%= form.radio_button :mode_of_transaction, 'Credit', :checked => true %> Credit
   <%= form.radio_button :mode_of_transaction, 'Debit' %> Debit
  </div>
  
<div>
    <label for="address">Amount<em>*</em></label>
   <%= form.text_field :amount %>
  </div>
<div><label for="date_of_birth "> Date<em>*</em></label>
       <%= form.date_select:date,:start_year => 1940 %>
 </div>
 <div class="buttonrow">
    <%= form.submit button_name ,:class=>'button'%>
  </div>
  </fieldset>
<% end %>
</div>

app/views/transactions/_recent_items.html.erb
<% for transaction in @recent_transactions %>
<li class="" id="recent_transaction_<%= transaction.id%>">
    <dt>   
		<%=link_to transaction.account_number,transaction_path(transaction)%>
    </dt>
    <tt>
       <br/>
    </tt>
</li>
<% end %>

app/views/transactions/_results.html.erb
<div id="transaction_list" class="list">
    <%if @transactions.blank? %>
    <div class="empty">There are no transactions yet..!</div>
    <%else %>
    <table width="100%">
        <tr>
            <td align="left">
                <h3 align="left"><%=@table_heading ||= 'Listing Transactions' %></h3>
            </td>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %> | <%= page_entries_info @transactions %>
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>

                <th>
                  <%= sortable 'account number' %>
                </th>
               
                <th>
                Bank Name
                  
                </th>
                <th>
                  Mode Of Transaction
                </th>
                
                <th>
                  Amount
                </th>
                <th>
                  Transaction Date
                </th>
                 <th>
                    Action
                </th>
        <%=render :partial=>'transaction',:collection=>@transactions %>
    </table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= will_paginate @transactions%>
    <% end %>
</div>

app/views/transactions/_transaction.html.erb
<%content_tag_for(:tr,transaction) do -%>
<td><%= link_to  transaction.account_number, transaction%></td>
<td><%=h transaction.bank_name %></td>
<td><%=h transaction.mode_of_transaction%></td>
<td><%=h transaction.amount%></td>
<td><%=h transaction.date.strftime("%d-%m-%Y")%></td>

<td>
<!--  <%= link_to 'Edit', edit_transaction_path(transaction) %> | -->
<!-- <%= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete %> | -->
    <%= link_to 'View', transaction %>
</td>
<% end %>

app/views/transactions/edit.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Update',:heading=>'Edit Bank'}%>
<div class="bottom_links">
<a href="@transactions" class="more">&larr; All Transactions</a>
  <%= link_to @transaction,:class=>'more' do %>
  Show Profile &uarr; 
 <% end %>
</div>

app/views/transactions/index.html.erb
<div id="markets">
    <%=render :partial=>'results' %>
</div>

app/views/transactions/new.html.erb
<%= render :partial=>'form',:locals=>{:button_name=>'Create',:heading=>'Create New transaction'} %>
<div class="bottom_links">
<a href="/transactions" class="more">All Transactions</a>
</div>

app/views/transactions/show.html.erb
<div class="form-container">
<fieldset>
<legend><b><%=@transaction.account_number %></b></legend>
<div>
   <label><b>Bank Name:</b></label>
  <%=h @transaction.bank_name %>
</div>
<hr/>
 
<div>
   <label><b>Account Number:</b></label>
 <%=h @transaction.account_number %>
</div>
<hr/>
<div>
   <label><b>Mode Of Transaction:</b></label>
 <%=h @transaction.mode_of_transaction %>
</div>
<hr/>

<div>
   <label><b>Amount:</b></label>
 <%=h @transaction.amount %>
</div>
<hr/>
</div>
<div class="bottom_links">
    <a href="/transactions" class="more">All Bank Transactions</a>
    &nbsp;&nbsp;
    <%=link_to new_transaction_path,:class=>'more' do %>
    Create New Bank Transaction
    <% end %>
</div>