config/routes.rb
Cscone::Application.routes.draw do

  

  resources :insurance_transactions do
  get 'export',:on=>:collection
end

 

  namespace :admin do resources :insurance_premia end
  
    namespace :admin do resources :reports do
      get 'banking',:on=>:collection
      get 'insurance',:on=>:collection
      get 'insurance_transaction',:on=>:collection
      get 'banking_transaction',:on=>:collection
      post 'banking_report',:on=>:collection
      post 'banking_transaction_report',:on=>:collection
      post 'insurance_report',:on=>:collection
      post  'insurance_transaction_report',:on=>:collection
    end
   end
  namespace :admin do resources :premia do
 get 'export',:on=>:collection
end
 end

  resources :transactions do
     get 'export',:on=>:collection
   end

  namespace :admin do resources :account_types do
 get 'export',:on=>:collection
end
end

  

  resources :insurances do
 get 'export',:on=>:collection
end

  resources :bankings do
     get 'export',:on=>:collection
     get 'edit_profile',:on=>:collection
     get 'show_profile',:on=>:collection
   end
 

  namespace :admin do resources :vle_representatives do
      get 'export',:on=>:collection
      get 'vle_user',:on=>:collection
      get 'vle_document',:on=>:collection
      get 'vle_report',:on=>:collection
       post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          post 'load_csc_blocks',:on=>:collection
          post 'load_vle_representatives',:on=>:collection
        get 'disable_representative',:on=>:collection
        get 'update_vle_representative',:on=>:collection
        get 'vle_profile',:on=>:collection
         get 'edit_profile',:on=>:collection
        post 'csv_import' , :on=>:collection
         get 'upload', :on=>:collection 
         get 'reset_password',:on=>:collection
          get 'upload_password',:on=>:collection
          get 'report',:on=>:collection
          get 'bulk_mailing' , :on=>:collection
          

      end
  end

  namespace :admin do
       resources :vle_documents do
           get 'export',:on=>:collection
       end
        end

  namespace :admin do
      resources :csc_blocks do
          get 'export',:on=>:collection
          post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          end
      end

  namespace :admin do
  resources :districts do
            get 'vle_document',:on=>:collection
      post 'load_bidding_zones',:on => :collection
  get 'export', :on=>:collection
       end
end
  namespace :admin do
  resources :bidding_zones do
    get 'export',:on=>:collection
    end
   end

  namespace :admin do
      resources :states do
          get 'export' ,:on=>:collection
           post 'csv_import', :on=>:collection
  get 'upload', :on=>:collection 
       end

      end
  
    resources :user_sessions
    
 namespace :admin do
 resources :users do
  get 'export',:on=>:collection
    end

  end
  resource :accout,:controller=>'users'
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/state.rb
class State < ActiveRecord::Base
    has_many :bidding_zones,:dependent=>:destroy
        has_many :districts,:dependent=>:destroy
        has_many :csc_blocks,:dependent=>:destroy
         has_many :vle_representative_profiles,:dependent=>:destroy
        validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 100}
        validates :description, :length => { :maximum => 2000}
    def self.search(search)
    if search
      where(:name.matches => "%#{search}%") #from meta_where gem
    else
      scoped
    end
  end
end

app/controllers/admin/states_controller.rb
require 'fastercsv'
class Admin::StatesController < ApplicationController
 helper_method :sort_column, :sort_direction
  layout 'admin'
  before_filter :require_user
  before_filter :recent_items
  # GET /admin/states
  # GET /admin/states.xml
  def index
    @states = State.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @states }
    end
  end

  # GET /admin/states/1
  # GET /admin/states/1.xml
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @state }
    end
  end

  # GET /admin/states/new
  # GET /admin/states/new.xml
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @state }
    end
  end

  # GET /admin/states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /admin/states
  # POST /admin/states.xml
  def create
    @state = State.new(params[:state])
     @state.created_by = @created_by
    respond_to do |format|
      if @state.save
        format.html { redirect_to([:admin,@state], :notice => 'State was successfully created.') }
        format.xml  { render :xml => @admin_state, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/states/1
  # PUT /admin/states/1.xml
  def update
    @state = State.find(params[:id])
     @state.updated_by = @updated_by
    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to([:admin,@state], :notice => 'State was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/states/1
  # DELETE /admin/states/1.xml
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to(admin_states_url) }
      format.xml  { head :ok }
    end
  end

     def export
    @states = State.search(params[:search]).order("name")
    outfile = "states" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["Name","Create at","Created By"]
      @states.each do |state|
        csv << [state.name,state.description,state.created_at.strftime('%d-%m-%Y %H:%M:%S'),User.find(state.created_by).name]
      end
    end
    send_data csv_data,
    :type => 'text/csv; charset=iso-8859-1; header=present',
    :disposition => "attachment; filename=#{outfile}"

  end
 private

  def recent_items
    @recent_states = State.find(:all,:limit=>10,:order=>'created_at DESC')
  end

  def sort_column
    State.column_names.include?(params[:sort]) ? params[:sort] : "description"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/admin/states/_form.html.erb
<div class="form-container">
    <% form_for([:admin,@state],:html=>{:class=>'cmxform'}) do |f| %>
    <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
    <fieldset>
        <legend>
            <%= heading %>
        </legend>
        <%= f.error_messages %>

        <div>
            <label for="name">
                Name <em>*</em>
            </label>
            <%= f.text_field :name %>
        </div>
        <div>
            <label for="description ">
                Description <em>*</em>
            </label>
            <%= f.text_area :description ,:cols=>28,:rows=>5 %>
        </div>
        <div class="buttonrow">
            <%= f.submit button_name ,:class=>'button' %>
        </div>
    </fieldset>
    <% end %>
</div>


app/views/admin/states/_recent_items.html.erb
<% for state in @recent_states %>
<li class="" id="recent_state_<%= state.id%>">
    <dt>
        <%=link_to truncate(state.name,:length=>27),admin_state_path(state) %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>


app/views/admin/states/_results.html.erb
<div id="state_list" class="list">
    <%if @states.blank? %>
    <div class="empty">There are No States Yet..!</div>
    <%else %>
    <table width="100%">
        <tr>
            <td align="left">
                <h3 align="left"><%=@table_heading ||= 'Listing States' %></h3>
            </td>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %> | <%= page_entries_info @states %>
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>

                <th>
                   <%= sortable 'name' %>
                </th>

                <th>
                    <%= sortable 'description' %>
                </th>
               <th><%= sortable "created_by" %></th>
		<th><%= sortable "created_at" %></th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <%=render :partial=>'state',:collection=>@states %>
    </table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= will_paginate @states %>
    <% end %>
</div>


app/views/admin/states/_state.html.erb
<%content_tag_for(:tr,state) do -%>
<td>
    <%=link_to(highlight(state.name,params[:search]),admin_state_path(state)) %>
</td>
<td>
    <%=h state.description %>
</td>
<td>
    <%=h @created_name %>
</td>
<td>
    <%=h state.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
</td>
<td>
    <%= link_to 'Edit', edit_admin_state_path(state) %> |
    <%= link_to 'Delete', [:admin,state], :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to 'View', [:admin,state] %>
</td>
<% end %>


app/views/admin/states/edit.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Update',:heading=>'Edit State'} %>
<div class="bottom_links">
    <a href="admin/states" class="more">&larr; All States</a>
    <%= link_to [:admin,@state],:class=>'more' do %>
    Show &uarr; <% end %>
</div>

app/views/admin/states/index.html.erb
<div id="markets">
    <%=render :partial=>'results' %>
</div>

app/views/admin/states/new.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Create',:heading=>'Create State'} %>
<div class="bottom_links">
    <a href="/admin/states" class="more">&larr; List All States</a>
</div>

app/views/admin/states/show.html.erb
<div class="form-container">
    <fieldset>
        <legend>
            <b><%= @state.name %></b>
        </legend>
        <div>
            <label>
                <b>Name:</b>
            </label>
            <%=h @state.name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Description:</b>
            </label>
            <%=h @state.description %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Created by:</b>
            </label>
            <%= User.find(@state.created_by).name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Created At:</b>
            </label>
            <%= @state.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
        </div>
        
    </fieldset>
</div>
<div class="bottom_links">
    <a href="/admin/states" class="more">&larr; All States</a>
    &nbsp;&nbsp;
    <%= link_to edit_admin_state_path(@state),:class=>'more' do %>
    Edit &uarr;
    <% end %>
    &nbsp;&nbsp;
    <%=link_to new_admin_state_path,:class=>'more' do %>
    Create New State &rarr;
    <% end %>
</div>